name: Content Request | 内容请求
description: Suggest a new piece of content or improvement to the project | 向该文档建议一个新内容或对已有内容的改进
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Which section does this content belong to? | 这个内容应属于哪个章节？
      description: A clear and concise description of which section this content belongs to. | 请清晰简洁地描述这个内容属于哪个章节。
      placeholder: |
        This content belongs to the "Chapter 0" section. | 这个内容属于 “Chapter 0” 章节。
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the content you'd like to see / improvement to that section | 描述你想要的内容 / 对该部分内容的改进
      description: A clear and concise description of the content you'd like to see or the improvement you'd like to see. | 请清晰简洁地描述你想要看到的内容或想要看到的改进。
      placeholder: |
        Add a section about awa in the documentation. | 在文档中添加一个关于 awa 的章节。
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context | 补充信息
      description: Add any other context or screenshots about the content request here. | 在这里添加任何其他上下文或截图。
    validations:
      required: false
