// Root layout: hosts <html>/<body>, global fonts, and the theme provider.
// next-themes ThemeProvider is placed here so it does NOT re-mount when
// switching [lang] segments, avoiding React 19 script warnings caused by
// client-side double-rendering of the theme script. Fumadocs' RootProvider
// also bundles a next-themes ThemeProvider by default — we disable it via
// `theme={{ enabled: false }}` in src/app/[lang]/layout.tsx so we don't end
// up nesting two providers (which is what was previously triggering the
// "script tag while rendering React component" warning).
// Real i18n translation injection is handled by src/app/[lang]/layout.tsx.
// Font strategy:
//   - Orbitron: Logo and numeric status marks (via --font-orbitron CSS variable)
//   - Noto Sans SC: Default body font
//   - Maple Mono NF CN: Code block font (local font)
// 根布局：承载 <html>/<body>、全局字体和主题提供器。
// next-themes 的 ThemeProvider 放在这里，确保切换 [lang] 段时它不会重新挂载，
// 从而避免主题脚本被客户端二次渲染触发 React 19 的 script 警告。
// fumadocs 的 RootProvider 默认也会包一层 next-themes ThemeProvider，
// 我们在 src/app/[lang]/layout.tsx 中通过 `theme={{ enabled: false }}` 将其关闭，
// 避免出现两个 Provider 嵌套（这是此前触发
// "script tag while rendering React component" 警告的根因）。
// 真正的多语言翻译注入由 src/app/[lang]/layout.tsx 完成。
// 字体策略：
//   - Orbitron：用于 Logo 与数字状态标识（通过 --font-orbitron CSS 变量）
//   - Noto Sans SC：正文默认字体
//   - Maple Mono NF CN：代码块字体（本地字体）

import { Noto_Sans_SC, Orbitron } from 'next/font/google';
import { ThemeProvider } from 'next-themes';
import { DeploymentSkewGuard } from '@/components/deployment-skew-guard';
import { ImmersiveInteractionController } from '@/components/immersive-interaction-controller';
import ImmersiveScrollbar from '@/components/immersive-scrollbar';
import { InlineCodeWrapController } from '@/components/inline-code-wrap-controller';
import { i18n } from '@/lib/i18n';
import '@/app/globals.css';
// Route loading styles are imported at the root CSS entry for Turbopack tracking.
// 路由加载样式在根 CSS 入口导入，确保 Turbopack 稳定追踪。
import '@/styles/loading.css';
// KaTeX styles render LaTeX formulas emitted by the MDX math pipeline.
// KaTeX 样式用于渲染 MDX 数学管线输出的 LaTeX 公式。
import 'katex/dist/katex.css';
// Maple Mono CN code font: loaded locally from the npm package instead of a
// render-blocking remote @import. The package CSS (generated by cn-font-split)
// declares hundreds of @font-face rules with unicode-range, so the browser
// only fetches the woff2 subsets needed for the characters actually rendered
// in code blocks — no full-font download upfront.
// Maple Mono CN 代码字体：从 npm 包本地加载，替代渲染阻塞的远程 @import。
// 包 CSS（由 cn-font-split 生成）声明了数百个带 unicode-range 的 @font-face
// 规则，浏览器仅获取代码块中实际渲染字符所需的 woff2 子集 —— 无需预下载
// 完整字体。
import '@mogeko/maple-mono-cn/dist/font/result.css';

const orbitron = Orbitron({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-orbitron',
});

const notoSansSC = Noto_Sans_SC({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-noto-sans',
});

// Enables the HTML-in-Canvas origin trial for docs.shenshijun.space and its subdomains.
// 为 docs.shenshijun.space 及其子域启用 HTML-in-Canvas Origin Trial。
const HTML_IN_CANVAS_ORIGIN_TRIAL_TOKEN =
  'Asl9H+KNGlrs0W5DtRf1ouCSdLl/pRmy4Xg6/AuxWRMADMfj8sKhuMAnubYnjc0TWGS25b/CIvMhOBnhwJX4tgEAAABueyJvcmlnaW4iOiJodHRwczovL2RvY3Muc2hlbnNoaWp1bi5zcGFjZTo0NDMiLCJmZWF0dXJlIjoiSFRNTEluQ2FudmFzIiwiZXhwaXJ5IjoxNzkyNDU0NDAwLCJpc1N1YmRvbWFpbiI6dHJ1ZX0=';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang={i18n.defaultLanguage} suppressHydrationWarning>
      <head>
        <meta httpEquiv="origin-trial" content={HTML_IN_CANVAS_ORIGIN_TRIAL_TOKEN} />
      </head>
      <body className={`antialiased min-h-screen ${orbitron.variable} ${notoSansSC.variable}`}>
        {/* Disable CSS transitions only while next-themes updates the root class.
            This prevents long documents from animating every theme-sensitive code block.
            仅在 next-themes 更新根主题类时暂停 CSS 过渡，
            避免长文档中的主题相关代码块同时参与动画。 */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
          enableSystem
        >
          <DeploymentSkewGuard />
          {/* Scoped light and particles provide activation feedback without page-level cursor tracking.
              局部光感与粒子提供激活反馈，不进行页面级光标跟踪。 */}
          <ImmersiveInteractionController />
          {/* Responsive inline-code detection distinguishes wrapped continuation fragments.
              响应式行内代码检测用于区分发生换行的续接片段。 */}
          <InlineCodeWrapController />
          {/* Custom viewport scrollbar removes the browser's default white gutter.
              自定义视口滚动条移除浏览器默认白色滚动槽。 */}
          <ImmersiveScrollbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
