import { createHash } from 'node:crypto';
import { mkdir, readdir, readFile, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import puppeteer, { type Page } from 'puppeteer';
import { getMermaidSourceId, normalizeMermaidSource } from '../src/lib/mermaid-asset-id';
import { MERMAID_CONFIG } from '../src/lib/mermaid-config';

const PROJECT_ROOT = process.cwd();
const CONTENT_ROOT = path.join(PROJECT_ROOT, 'content', 'docs');
const ASSET_ROOT = path.join(PROJECT_ROOT, 'public', 'mermaid');
const MANIFEST_PATH = path.join(PROJECT_ROOT, 'src', 'generated', 'mermaid-assets.ts');
const MERMAID_STYLE_PATH = path.join(PROJECT_ROOT, 'src', 'styles', 'mermaid.css');
const MERMAID_BROWSER_BUNDLE = path.join(
  PROJECT_ROOT,
  'node_modules',
  'mermaid',
  'dist',
  'mermaid.min.js',
);
const RENDERER_VERSION = 'project-mermaid-11.16.1-site-context-v2';

interface BrowserMermaidApi {
  initialize: (config: unknown) => void;
  render: (id: string, source: string, container?: HTMLElement) => Promise<{ svg: string }>;
}

async function findContentFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map(async (entry) => {
      const entryPath = path.join(directory, entry.name);
      if (entry.isDirectory()) return findContentFiles(entryPath);
      return /\.mdx?$/.test(entry.name) ? [entryPath] : [];
    }),
  );
  return nested.flat();
}

function isClosingFence(line: string, marker: string): boolean {
  const trimmed = line.trim();
  if (trimmed.length < marker.length) return false;
  return [...trimmed].every((character) => character === marker[0]);
}

function extractMermaidBlocks(markdown: string): string[] {
  const lines = markdown.replace(/\r\n?/g, '\n').split('\n');
  const blocks: string[] = [];

  for (let index = 0; index < lines.length; index += 1) {
    const opening = lines[index]?.match(/^ {0,3}(`{3,}|~{3,})[ \t]*mermaid(?:[ \t]+.*)?$/);
    if (!opening) continue;

    const marker = opening[1];
    const body: string[] = [];
    for (index += 1; index < lines.length; index += 1) {
      const line = lines[index] ?? '';
      if (isClosingFence(line, marker)) break;
      body.push(line);
    }

    const source = normalizeMermaidSource(body.join('\n'));
    if (source) blocks.push(source);
  }

  return blocks;
}

function createAssetName(source: string): string {
  const signature = JSON.stringify({
    renderer: RENDERER_VERSION,
    config: MERMAID_CONFIG,
    source,
  });
  return `${createHash('sha256').update(signature).digest('hex').slice(0, 24)}.svg`;
}

function createManifest(entries: ReadonlyMap<string, string>): string {
  const properties = [...entries]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([sourceId, fileName]) => `  '${sourceId}': '${fileName}',`)
    .join('\n');

  return [
    '// Generated by scripts/generate-mermaid-assets.ts. Do not edit manually.',
    '// 由 scripts/generate-mermaid-assets.ts 生成，请勿手动修改。',
    'export const MERMAID_ASSET_PATHS: Readonly<Record<string, string>> = {',
    properties,
    '};',
    '',
  ].join('\n');
}

async function removeStaleGeneratedAssets(activeFileNames: ReadonlySet<string>): Promise<number> {
  const entries = await readdir(ASSET_ROOT, { withFileTypes: true });
  const stale = entries.filter(
    (entry) =>
      entry.isFile() && /^[0-9a-f]{24}\.svg$/.test(entry.name) && !activeFileNames.has(entry.name),
  );
  await Promise.all(stale.map((entry) => unlink(path.join(ASSET_ROOT, entry.name))));
  return stale.length;
}

async function createRendererPage(): Promise<Page> {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const mermaidStyle = await readFile(MERMAID_STYLE_PATH, 'utf8');
  await page.setViewport({ width: 1280, height: 800, deviceScaleFactor: 1 });
  await page.setContent(`<!doctype html>
    <html>
      <head>
        <style>
          html, body {
            margin: 0;
            font-family: "Noto Sans SC", "PingFang SC", "Microsoft YaHei", "Noto Sans", sans-serif;
          }

          #mermaid-build-host {
            position: fixed;
            left: -100000px;
            top: 0;
            visibility: hidden;
          }
        </style>
      </head>
      <body><div id="mermaid-build-host" class="mermaid-svg-host"></div></body>
    </html>`);
  await page.addStyleTag({ content: mermaidStyle });
  await page.addScriptTag({ path: MERMAID_BROWSER_BUNDLE });
  await page.evaluate(async (config) => {
    const runtime = (globalThis as typeof globalThis & { mermaid?: BrowserMermaidApi }).mermaid;
    if (!runtime) throw new Error('Project Mermaid browser bundle did not initialize.');
    await document.fonts.ready;
    runtime.initialize(config);
  }, MERMAID_CONFIG);
  return page;
}

async function renderWithProjectMermaid(
  page: Page,
  sourceId: string,
  source: string,
): Promise<string> {
  return page.evaluate(
    async ({ id, definition }) => {
      const runtime = (globalThis as typeof globalThis & { mermaid?: BrowserMermaidApi }).mermaid;
      if (!runtime) throw new Error('Project Mermaid browser bundle is unavailable.');

      const renderId = `mermaid-${id}`;
      const host = document.getElementById('mermaid-build-host');
      if (!(host instanceof HTMLElement)) throw new Error('Mermaid build host is unavailable.');
      host.replaceChildren();
      try {
        const { svg } = await runtime.render(renderId, definition, host);
        return svg;
      } finally {
        document.getElementById(`d${renderId}`)?.remove();
      }
    },
    { id: sourceId, definition: source },
  );
}

async function main(): Promise<void> {
  const files = await findContentFiles(CONTENT_ROOT);
  const charts = new Map<string, string>();

  for (const file of files) {
    const markdown = await readFile(file, 'utf8');
    for (const source of extractMermaidBlocks(markdown)) {
      const sourceId = getMermaidSourceId(source);
      const existing = charts.get(sourceId);
      if (existing && existing !== source) {
        throw new Error(`Mermaid source hash collision: ${sourceId}`);
      }
      charts.set(sourceId, source);
    }
  }

  await mkdir(ASSET_ROOT, { recursive: true });
  await mkdir(path.dirname(MANIFEST_PATH), { recursive: true });

  const manifest = new Map<string, string>();
  const pending: Array<{ sourceId: string; source: string; fileName: string }> = [];
  for (const [sourceId, source] of charts) {
    const fileName = createAssetName(source);
    manifest.set(sourceId, fileName);
    try {
      await readFile(path.join(ASSET_ROOT, fileName));
    } catch {
      pending.push({ sourceId, source, fileName });
    }
  }

  if (pending.length > 0) {
    const page = await createRendererPage();
    try {
      for (const item of pending) {
        const svg = await renderWithProjectMermaid(page, item.sourceId, item.source);
        await writeFile(path.join(ASSET_ROOT, item.fileName), svg, 'utf8');
      }
    } finally {
      await page.browser().close();
    }
  }

  await writeFile(MANIFEST_PATH, createManifest(manifest), 'utf8');
  const removed = await removeStaleGeneratedAssets(new Set(manifest.values()));
  console.info(
    `Mermaid assets: ${charts.size} total, ${pending.length} generated, ${charts.size - pending.length} reused, ${removed} stale removed.`,
  );
}

await main();
