import { createHash } from 'node:crypto';
import { mkdir, readdir, readFile, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import puppeteer, { type Browser, type Page } from 'puppeteer';
import {
  getMermaidSourceId,
  MERMAID_CONFIG,
  normalizeMermaidSource,
} from '../src/features/mermaid';

const PROJECT_ROOT = process.cwd();
const CONTENT_ROOT = path.join(PROJECT_ROOT, 'content', 'docs');
const ASSET_ROOT = path.join(PROJECT_ROOT, 'public', 'mermaid');
const MANIFEST_PATH = path.join(
  PROJECT_ROOT,
  'src',
  'features',
  'mermaid',
  'generated',
  'assets.ts',
);
const MERMAID_STYLE_PATH = path.join(PROJECT_ROOT, 'src', 'features', 'mermaid', 'styles.css');
const MERMAID_BROWSER_BUNDLE = path.join(
  PROJECT_ROOT,
  'node_modules',
  'mermaid',
  'dist',
  'mermaid.min.js',
);
const ALLOW_CLIENT_FALLBACK = process.argv.includes('--allow-client-fallback');

interface BrowserMermaidApi {
  initialize: (config: unknown) => void;
  render: (id: string, source: string, container?: HTMLElement) => Promise<{ svg: string }>;
}

async function findContentFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map(async (entry) => {
      const entryPath = path.join(directory, entry.name);
      if (entry.isDirectory()) return findContentFiles(entryPath);
      return /\.mdx?$/.test(entry.name) ? [entryPath] : [];
    }),
  );
  return nested.flat();
}

function isClosingFence(line: string, marker: string): boolean {
  const trimmed = line.trim();
  if (trimmed.length < marker.length) return false;
  return [...trimmed].every((character) => character === marker[0]);
}

function extractMermaidBlocks(markdown: string): string[] {
  const lines = markdown.replace(/\r\n?/g, '\n').split('\n');
  const blocks: string[] = [];

  for (let index = 0; index < lines.length; index += 1) {
    const opening = lines[index]?.match(/^ {0,3}(`{3,}|~{3,})[ \t]*mermaid(?:[ \t]+.*)?$/);
    if (!opening) continue;

    const marker = opening[1];
    const body: string[] = [];
    for (index += 1; index < lines.length; index += 1) {
      const line = lines[index] ?? '';
      if (isClosingFence(line, marker)) break;
      body.push(line);
    }

    const source = normalizeMermaidSource(body.join('\n'));
    if (source) blocks.push(source);
  }

  return blocks;
}

// Asset validity is content-addressed over every renderer input: the browser
// bundle, the metric-sensitive styles and the shared config. Any of them
// changing re-hashes asset names, so stale SVGs can never be silently reused
// and no manual version string needs bumping.
// 资产有效性按渲染输入内容寻址：浏览器 bundle、度量样式与共享配置任一变化
// 都会改变资产名哈希，因此不会静默复用过期 SVG，也无需手工维护版本号。
async function computeRendererSignature(): Promise<string> {
  const [styleCss, browserBundle] = await Promise.all([
    readFile(MERMAID_STYLE_PATH, 'utf8'),
    readFile(MERMAID_BROWSER_BUNDLE, 'utf8'),
  ]);
  return createHash('sha256')
    .update('nd-mermaid-renderer\0')
    .update(styleCss)
    .update('\0')
    .update(browserBundle)
    .digest('hex')
    .slice(0, 16);
}

function createAssetName(source: string, rendererSignature: string): string {
  const signature = JSON.stringify({
    renderer: rendererSignature,
    config: MERMAID_CONFIG,
    source,
  });
  return `${createHash('sha256').update(signature).digest('hex').slice(0, 24)}.svg`;
}

function createManifest(entries: ReadonlyMap<string, string>): string {
  const properties = [...entries]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([sourceId, fileName]) => `  '${sourceId}': '${fileName}',`)
    .join('\n');

  return [
    '// Generated by scripts/generate-mermaid-assets.ts. Do not edit manually.',
    '// 由 scripts/generate-mermaid-assets.ts 生成，请勿手动修改。',
    'export const MERMAID_ASSET_PATHS: Readonly<Record<string, string>> = {',
    properties,
    '};',
    '',
  ].join('\n');
}

async function removeStaleGeneratedAssets(activeFileNames: ReadonlySet<string>): Promise<number> {
  const entries = await readdir(ASSET_ROOT, { withFileTypes: true });
  const stale = entries.filter(
    (entry) =>
      entry.isFile() && /^[0-9a-f]{24}\.svg$/.test(entry.name) && !activeFileNames.has(entry.name),
  );
  await Promise.all(stale.map((entry) => unlink(path.join(ASSET_ROOT, entry.name))));
  return stale.length;
}

async function createRendererPage(browser: Browser): Promise<Page> {
  const page = await browser.newPage();
  const mermaidStyle = await readFile(MERMAID_STYLE_PATH, 'utf8');
  await page.setViewport({ width: 1280, height: 800, deviceScaleFactor: 1 });
  await page.setContent(`<!doctype html>
    <html>
      <head>
        <style>
          html, body {
            margin: 0;
            font-family: "Noto Sans SC", "PingFang SC", "Microsoft YaHei", "Noto Sans", sans-serif;
          }

          #mermaid-build-host {
            position: fixed;
            left: -100000px;
            top: 0;
            visibility: hidden;
          }
        </style>
      </head>
      <body><div id="mermaid-build-host" class="mermaid-svg-host"></div></body>
    </html>`);
  await page.addStyleTag({ content: mermaidStyle });
  await page.addScriptTag({ path: MERMAID_BROWSER_BUNDLE });
  await page.evaluate(async (config) => {
    const runtime = (globalThis as typeof globalThis & { mermaid?: BrowserMermaidApi }).mermaid;
    if (!runtime) throw new Error('Project Mermaid browser bundle did not initialize.');
    await document.fonts.ready;
    runtime.initialize(config);
  }, MERMAID_CONFIG);
  return page;
}

async function launchRendererBrowser(): Promise<Browser | null> {
  try {
    return await puppeteer.launch();
  } catch (error) {
    if (!ALLOW_CLIENT_FALLBACK) throw error;

    const summary = error instanceof Error ? error.message.split('\n')[0] : String(error);
    console.warn(
      `Mermaid static renderer unavailable; missing charts will use the client renderer. ${summary}`,
    );
    return null;
  }
}

async function renderWithProjectMermaid(
  page: Page,
  sourceId: string,
  source: string,
): Promise<string> {
  return page.evaluate(
    async ({ id, definition }) => {
      const runtime = (globalThis as typeof globalThis & { mermaid?: BrowserMermaidApi }).mermaid;
      if (!runtime) throw new Error('Project Mermaid browser bundle is unavailable.');

      const renderId = `mermaid-${id}`;
      const host = document.getElementById('mermaid-build-host');
      if (!(host instanceof HTMLElement)) throw new Error('Mermaid build host is unavailable.');
      host.replaceChildren();
      try {
        const { svg } = await runtime.render(renderId, definition, host);
        return svg;
      } finally {
        document.getElementById(`d${renderId}`)?.remove();
      }
    },
    { id: sourceId, definition: source },
  );
}

async function main(): Promise<void> {
  let renderSeconds = '0';
  // Phase timing uses the monotonic hrtime clock: on some Windows hosts both
  // wall-clock and performance.now() deltas were observed inflating wildly
  // under build load, while hrtime stayed accurate. Timings are best-effort
  // diagnostics, never correctness inputs.
  // 阶段计时使用单调 hrtime 时钟：某些 Windows 宿主在构建负载下曾出现
  // 墙钟与 performance.now() 差值严重虚高的现象，而 hrtime 保持准确。
  // 计时是尽力而为的诊断信息，绝不参与正确性判断。
  const totalStartedAt = process.hrtime.bigint();
  const scanStartedAt = process.hrtime.bigint();
  const files = await findContentFiles(CONTENT_ROOT);
  const charts = new Map<string, string>();

  for (const file of files) {
    const markdown = await readFile(file, 'utf8');
    for (const source of extractMermaidBlocks(markdown)) {
      const sourceId = getMermaidSourceId(source);
      const existing = charts.get(sourceId);
      if (existing && existing !== source) {
        throw new Error(`Mermaid source hash collision: ${sourceId}`);
      }
      charts.set(sourceId, source);
    }
  }
  const scanSeconds = elapsedSeconds(scanStartedAt);

  const rendererSignature = await computeRendererSignature();

  await mkdir(ASSET_ROOT, { recursive: true });
  await mkdir(path.dirname(MANIFEST_PATH), { recursive: true });

  const manifest = new Map<string, string>();
  const pending: Array<{ sourceId: string; source: string; fileName: string }> = [];
  let generatedCount = 0;
  let clientFallbackCount = 0;
  for (const [sourceId, source] of charts) {
    const fileName = createAssetName(source, rendererSignature);
    manifest.set(sourceId, fileName);
    try {
      await readFile(path.join(ASSET_ROOT, fileName));
    } catch {
      pending.push({ sourceId, source, fileName });
    }
  }

  if (pending.length > 0) {
    const renderStartedAt = process.hrtime.bigint();
    const browser = await launchRendererBrowser();
    if (browser) {
      try {
        const page = await createRendererPage(browser);
        for (const item of pending) {
          const svg = await renderWithProjectMermaid(page, item.sourceId, item.source);
          await writeFile(path.join(ASSET_ROOT, item.fileName), svg, 'utf8');
          generatedCount += 1;
        }
      } finally {
        await browser.close();
      }
      renderSeconds = elapsedSeconds(renderStartedAt);
    } else {
      // Do not publish manifest entries for files that were not generated.
      // The existing browser renderer will handle only these missing charts.
      // 不为未生成的文件发布清单项，仅让现有浏览器渲染器处理这些缺失图表。
      for (const item of pending) manifest.delete(item.sourceId);
      clientFallbackCount = pending.length;
    }
  }

  const cleanupStartedAt = process.hrtime.bigint();
  await writeFile(MANIFEST_PATH, createManifest(manifest), 'utf8');
  const removed = await removeStaleGeneratedAssets(new Set(manifest.values()));
  const cleanupSeconds = elapsedSeconds(cleanupStartedAt);

  const clientFallbackSummary =
    clientFallbackCount > 0 ? `, ${clientFallbackCount} client fallback` : '';
  console.info(
    `Mermaid assets: ${charts.size} total, ${generatedCount} generated, ${charts.size - pending.length} reused${clientFallbackSummary}, ${removed} stale removed ` +
      `(scan ${scanSeconds}s, render ${renderSeconds}s, cleanup ${cleanupSeconds}s, total ${elapsedSeconds(totalStartedAt)}s, max rss ${maxRssMb()}MB).`,
  );
}

function elapsedSeconds(startedAtNs: bigint): string {
  return (Number(process.hrtime.bigint() - startedAtNs) / 1e9).toFixed(2);
}

// Peak resident set of this script only; the headless Chromium spawned for
// rendering is a separate process and is not visible here.
// 仅统计本脚本进程的峰值驻留内存；渲染用的无头 Chromium 是独立进程，不在此列。
function maxRssMb(): number {
  const usage =
    typeof process.resourceUsage === 'function' ? process.resourceUsage() : undefined;
  const maxRssBytes = usage ? usage.maxRSS * 1024 : process.memoryUsage().rss;
  return Math.round(maxRssBytes / 1024 / 1024);
}

await main();
