// Shared mermaid asset logic for the content pipeline: content-addressed file
// naming, manifest serialization and stale cleanup. No puppeteer import here
// so the verify mode of scripts/content-pipeline.ts can hash-check assets
// without ever loading the renderer. Naming logic must stay byte-stable —
// changing it re-hashes every asset name and invalidates the committed SVGs.
// 内容管线共享的 Mermaid 资产逻辑：内容寻址的文件命名、清单序列化与失效
// 清理。此处不引入 puppeteer，scripts/content-pipeline.ts 的 verify 模式
// 因此可以在完全不加载渲染器的情况下校验资产哈希。命名逻辑必须保持字节
// 稳定 —— 任何改动都会重哈希全部资产名并使已提交的 SVG 失效。
import { createHash } from 'node:crypto';
import { readdir, readFile, unlink } from 'node:fs/promises';
import path from 'node:path';
import { MERMAID_CONFIG } from '../src/features/mermaid';
import { getMermaidSourceId, normalizeMermaidSource } from '../src/lib/mermaid-id';

export const PROJECT_ROOT = process.cwd();
export const ASSET_ROOT = path.join(PROJECT_ROOT, 'public', 'mermaid');
export const MANIFEST_PATH = path.join(
  PROJECT_ROOT,
  'src',
  'features',
  'mermaid',
  'generated',
  'assets.ts',
);
const MERMAID_STYLE_PATH = path.join(PROJECT_ROOT, 'src', 'features', 'mermaid', 'styles.css');
const MERMAID_BROWSER_BUNDLE = path.join(
  PROJECT_ROOT,
  'node_modules',
  'mermaid',
  'dist',
  'mermaid.min.js',
);

export interface MermaidChart {
  sourceId: string;
  source: string;
}

// Deduplicates diagram sources from the Content IR by stable source ID. The
// collision guard keeps the 64-bit FNV id trustworthy: two different sources
// mapping to one id would silently share an asset.
// 按稳定源码 ID 对来自 Content IR 的图表源码去重。冲突防护保证 64 位 FNV
// 标识的可信度：两个不同源码映射到同一标识会静默共享同一资产。
export function dedupeCharts(sources: Iterable<string>): Map<string, MermaidChart> {
  const charts = new Map<string, MermaidChart>();
  for (const source of sources) {
    const normalized = normalizeMermaidSource(source);
    const sourceId = getMermaidSourceId(normalized);
    const existing = charts.get(sourceId);
    if (existing && existing.source !== normalized) {
      throw new Error(`Mermaid source hash collision: ${sourceId}`);
    }
    charts.set(sourceId, { sourceId, source: normalized });
  }
  return charts;
}

// Asset validity is content-addressed over every renderer input: the browser
// bundle, the metric-sensitive styles and the shared config. Any of them
// changing re-hashes asset names, so stale SVGs can never be silently reused
// and no manual version string needs bumping.
// 资产有效性按渲染输入内容寻址：浏览器 bundle、度量样式与共享配置任一变化
// 都会改变资产名哈希，因此不会静默复用过期 SVG，也无需手工维护版本号。
export async function computeRendererSignature(): Promise<string> {
  const [styleCss, browserBundle] = await Promise.all([
    readFile(MERMAID_STYLE_PATH, 'utf8'),
    readFile(MERMAID_BROWSER_BUNDLE, 'utf8'),
  ]);
  return createHash('sha256')
    .update('nd-mermaid-renderer\0')
    .update(styleCss)
    .update('\0')
    .update(browserBundle)
    .digest('hex')
    .slice(0, 16);
}

export function createAssetName(source: string, rendererSignature: string): string {
  const signature = JSON.stringify({
    renderer: rendererSignature,
    config: MERMAID_CONFIG,
    source,
  });
  return `${createHash('sha256').update(signature).digest('hex').slice(0, 24)}.svg`;
}

export function createManifestSource(entries: ReadonlyMap<string, string>): string {
  const properties = [...entries]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([sourceId, fileName]) => `  '${sourceId}': '${fileName}',`)
    .join('\n');

  return [
    '// Generated by the mermaid generate stage of scripts/content-pipeline.ts. Do not edit manually.',
    '// 由 scripts/content-pipeline.ts 的 mermaid generate 阶段生成，请勿手动修改。',
    'export const MERMAID_ASSET_PATHS: Readonly<Record<string, string>> = {',
    properties,
    '};',
    '',
  ].join('\n');
}

export async function removeStaleGeneratedAssets(
  activeFileNames: ReadonlySet<string>,
): Promise<number> {
  const entries = await readdir(ASSET_ROOT, { withFileTypes: true });
  const stale = entries.filter(
    (entry) =>
      entry.isFile() && /^[0-9a-f]{24}\.svg$/.test(entry.name) && !activeFileNames.has(entry.name),
  );
  await Promise.all(stale.map((entry) => unlink(path.join(ASSET_ROOT, entry.name))));
  return stale.length;
}

export async function assetExists(fileName: string): Promise<boolean> {
  try {
    await readFile(path.join(ASSET_ROOT, fileName));
    return true;
  } catch {
    return false;
  }
}
