/**
 * Custom code block that always renders a top header bar with:
 * - Language icon (from Shiki transformerIcon)
 * - File path (only when set via remark-code-title)
 * - Runtime fallback for stale MDX output that still contains a path comment
 * - Copy button
 *
 * 自定义代码块，始终渲染顶部横条，包含：
 * - 编程语言图标（由 Shiki transformerIcon 设置）
 * - 文件路径（仅当通过 remark-code-title 设置时显示）
 * - 对仍保留路径注释的旧 MDX 输出做运行时兜底
 * - 复制按钮
 */

'use client';

// fumadocs-ui 16.11+ moved useTranslations to @fuma-translate/react and changed
// its API from a keyed object to a callable translation function.
// fumadocs-ui 16.11+ 将 useTranslations 迁移至 @fuma-translate/react，API 由对象改为可调用函数。
import { useTranslations } from '@fuma-translate/react';
import { Pre } from 'fumadocs-ui/components/codeblock';
import { useCopyButton } from 'fumadocs-ui/utils/use-copy-button';
import { Check, Clipboard } from 'lucide-react';
import {
  Children,
  type ComponentProps,
  cloneElement,
  isValidElement,
  type ReactElement,
  type ReactNode,
  useRef,
} from 'react';
import { getFilePathFromCodeTitleLine } from '@/lib/code-title';
import { getLanguageDisplayName } from '@/lib/language-mapping';

interface CodeBlockPreProps extends ComponentProps<'pre'> {
  title?: string;
  icon?: ReactNode | string;
  lang?: string;
  /** Shiki line-numbers transformer flags, spread onto the <pre> element. */
  /** Shiki 行号 transformer 标记，展开到 <pre> 元素上。 */
  'data-line-numbers'?: string;
  'data-line-numbers-start'?: string;
}

export function CustomCodeBlock(props: CodeBlockPreProps) {
  const { children, title, icon, lang, className, ...rest } = props;
  const areaRef = useRef<HTMLDivElement>(null);
  const fallbackTitle =
    typeof title === 'string' && title.length > 0 ? null : getFallbackTitle(children);
  const codeTitle = typeof title === 'string' && title.length > 0 ? title : fallbackTitle;
  const hasTitle = typeof codeTitle === 'string' && codeTitle.length > 0;
  const codeChildren = fallbackTitle ? stripFallbackTitleLine(children) : children;
  const language = typeof lang === 'string' ? getLanguageDisplayName(lang) : null;

  // Glass code block wrapper keeps page ambient colors visible without changing Shiki markup.
  // 代码块玻璃外壳在不改变 Shiki 结构的前提下，让页面环境色保持可见。
  return (
    <figure
      dir="ltr"
      tabIndex={-1}
      className={`my-4 glass-codeblock rounded-xl shiki relative not-prose overflow-hidden text-sm ${className || ''}`}
      {...rest}
    >
      <div className="flex text-fd-muted-foreground items-center gap-2 h-9.5 border-b px-4">
        {typeof icon === 'string' ? (
          // biome-ignore lint/security/noDangerouslySetInnerHtml: icon HTML is generated by fumadocs Shiki transformer
          <div className="[&_svg]:size-3.5" dangerouslySetInnerHTML={{ __html: icon }} />
        ) : icon ? (
          <div className="[&_svg]:size-3.5">{icon}</div>
        ) : null}
        {hasTitle ? (
          <figcaption className="flex-1 truncate">{codeTitle}</figcaption>
        ) : language ? (
          <span className="flex-1 text-xs font-medium">{language}</span>
        ) : (
          <span className="flex-1" />
        )}
        <CopyButton containerRef={areaRef} />
      </div>
      {/* biome-ignore lint/a11y/useSemanticElements: region role matches fumadocs CodeBlock */}
      <div
        ref={areaRef}
        role="region"
        // biome-ignore lint/a11y/noNoninteractiveTabindex: matches fumadocs CodeBlock behavior
        tabIndex={0}
        className="text-[0.8125rem] py-3.5 overflow-auto max-h-[600px] fd-scroll-container focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-fd-ring"
        style={{
          counterSet: rest['data-line-numbers']
            ? `line ${Number(rest['data-line-numbers-start'] ?? 1) - 1}`
            : undefined,
        }}
      >
        <Pre>{codeChildren}</Pre>
      </div>
    </figure>
  );
}

function getFallbackTitle(children: ReactNode) {
  const firstLine = getTextContent(children).split(/\r?\n/)[0] ?? '';

  return getFilePathFromCodeTitleLine(firstLine);
}

function getTextContent(node: ReactNode): string {
  if (typeof node === 'string' || typeof node === 'number') return String(node);
  if (Array.isArray(node)) return node.map(getTextContent).join('');
  if (isValidElement<{ children?: ReactNode }>(node)) return getTextContent(node.props.children);

  return '';
}

function stripFallbackTitleLine(children: ReactNode) {
  const state = { stripped: false };

  return stripFirstCodeLine(children, state);
}

function stripFirstCodeLine(node: ReactNode, state: { stripped: boolean }): ReactNode {
  if (state.stripped || node == null || typeof node === 'boolean') return node;
  if (Array.isArray(node)) return node.map((child) => stripFirstCodeLine(child, state));
  if (!isValidElement<{ children?: ReactNode }>(node)) return node;

  const element = node as ReactElement<{ children?: ReactNode }>;
  const nextChildren =
    element.type === 'code'
      ? stripFirstLineChildren(element.props.children, state)
      : stripFirstCodeLine(element.props.children, state);

  if (nextChildren === element.props.children) return node;

  return cloneElement(element, undefined, nextChildren);
}

function stripFirstLineChildren(children: ReactNode, state: { stripped: boolean }) {
  const nextChildren: ReactNode[] = [];
  let consumedFirstLine = false;
  let shouldDropLeadingBreak = false;

  state.stripped = true;

  for (const child of Children.toArray(children)) {
    if (!consumedFirstLine) {
      consumedFirstLine = true;

      if (typeof child === 'string') {
        const remainingText = child.replace(/^[^\r\n]*(?:\r?\n)?/, '');
        if (remainingText.length > 0) nextChildren.push(remainingText);
      } else {
        shouldDropLeadingBreak = true;
      }

      continue;
    }

    if (shouldDropLeadingBreak && typeof child === 'string') {
      const remainingText = child.replace(/^\r?\n/, '');
      shouldDropLeadingBreak = false;
      if (remainingText.length > 0) nextChildren.push(remainingText);
      continue;
    }

    shouldDropLeadingBreak = false;
    nextChildren.push(child);
  }

  return nextChildren;
}

function CopyButton({ containerRef }: { containerRef: React.RefObject<HTMLDivElement | null> }) {
  const t = useTranslations();
  const [checked, onClick] = useCopyButton(() => {
    const pre = containerRef.current?.getElementsByTagName('pre').item(0);
    if (!pre) return;
    const clone = pre.cloneNode(true) as HTMLElement;
    clone.querySelectorAll('.nd-copy-ignore').forEach((node) => {
      node.replaceWith('\n');
    });
    navigator.clipboard.writeText(clone.textContent ?? '');
  });

  return (
    <button
      type="button"
      data-checked={checked || undefined}
      className="inline-flex items-center justify-center rounded-md p-1 text-fd-muted-foreground hover:text-fd-accent-foreground hover:bg-fd-accent data-checked:text-green-600 data-checked:bg-green-500/10 dark:data-checked:text-green-400 dark:data-checked:bg-green-500/15 transition-all duration-200 cursor-pointer active:scale-95"
      aria-label={
        checked ? t('Copied Text(code block)(aria-label)') : t('Copy Text(code block)(aria-label)')
      }
      onClick={onClick}
    >
      {checked ? (
        <Check className="size-3.5 animate-in zoom-in-50 duration-200" />
      ) : (
        <Clipboard className="size-3.5" />
      )}
    </button>
  );
}
