/**
 * Custom code block that always renders a top header bar with:
 * - Language icon (from Shiki transformerIcon)
 * - File path (only when set via remark-code-title)
 * - Runtime fallback for stale MDX output that still contains a path comment
 * - A minimal client-only copy button
 *
 * 自定义代码块，始终渲染顶部横条，包含：
 * - 编程语言图标（由 Shiki transformerIcon 设置）
 * - 文件路径（仅当通过 remark-code-title 设置时显示）
 * - 对仍保留路径注释的旧 MDX 输出做运行时兜底
 * - 最小化客户端边界的复制按钮
 */

import {
  Children,
  type ComponentProps,
  cloneElement,
  isValidElement,
  type ReactElement,
  type ReactNode,
} from 'react';
import { CodeCopyButton } from '@/components/mdx/code-copy-button';
import { getFilePathFromCodeTitleLine } from '@/content/plugins/code-title';
import { getLanguageDisplayName } from '@/lib/language-mapping';

interface CodeBlockPreProps extends ComponentProps<'pre'> {
  title?: string;
  icon?: ReactNode | string;
  lang?: string;
  /** Shiki line-numbers transformer flags, spread onto the <pre> element. */
  /** Shiki 行号 transformer 标记，展开到 <pre> 元素上。 */
  'data-line-numbers'?: string;
  'data-line-numbers-start'?: string;
}

interface LongCodeBlockProps {
  code: string;
  lang?: string;
  title?: string;
}

export function LongCodeBlock({ code, lang, title }: LongCodeBlockProps) {
  return (
    <CustomCodeBlock className="docs-long-codeblock" lang={lang} title={title}>
      <code className={lang ? `language-${lang}` : undefined}>
        <span className="docs-long-codeblock__content">{code}</span>
      </code>
    </CustomCodeBlock>
  );
}

export function CustomCodeBlock(props: CodeBlockPreProps) {
  const { children, title, icon, lang, className, ...rest } = props;

  const fallbackTitle =
    typeof title === 'string' && title.length > 0 ? null : getFallbackTitle(children);
  const codeTitle = typeof title === 'string' && title.length > 0 ? title : fallbackTitle;
  const hasTitle = typeof codeTitle === 'string' && codeTitle.length > 0;
  const codeChildren = fallbackTitle ? stripFallbackTitleLine(children) : children;
  const language = typeof lang === 'string' ? getLanguageDisplayName(lang) : null;

  // Glass code block wrapper keeps page ambient colors visible without changing Shiki markup.
  // 代码块玻璃外壳在不改变 Shiki 结构的前提下，让页面环境色保持可见。
  return (
    <figure
      dir="ltr"
      tabIndex={-1}
      className={`my-4 glass-codeblock rounded-xl shiki relative not-prose overflow-hidden text-sm ${className || ''}`}
      data-nd-interaction="surface"
      {...rest}
    >
      <div className="flex text-fd-muted-foreground items-center gap-2 h-9.5 border-b px-4">
        {typeof icon === 'string' ? (
          // biome-ignore lint/security/noDangerouslySetInnerHtml: icon HTML is generated by fumadocs Shiki transformer
          <div className="[&_svg]:size-3.5" dangerouslySetInnerHTML={{ __html: icon }} />
        ) : icon ? (
          <div className="[&_svg]:size-3.5">{icon}</div>
        ) : null}
        {hasTitle ? (
          <figcaption className="flex-1 truncate">{codeTitle}</figcaption>
        ) : language ? (
          <span className="flex-1 text-xs font-medium">{language}</span>
        ) : (
          <span className="flex-1" />
        )}
        <CodeCopyButton />
      </div>
      {/* biome-ignore lint/a11y/useSemanticElements: region role matches fumadocs CodeBlock */}
      <div
        role="region"
        // biome-ignore lint/a11y/noNoninteractiveTabindex: matches fumadocs CodeBlock behavior
        tabIndex={0}
        className="text-[0.8125rem] py-3.5 overflow-auto max-h-150 fd-scroll-container focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-fd-ring"
        style={{
          counterSet: rest['data-line-numbers']
            ? `line ${Number(rest['data-line-numbers-start'] ?? 1) - 1}`
            : undefined,
        }}
      >
        {/* Fumadocs `Pre` only adds these layout classes but is a client component.
            Rendering the equivalent native element keeps highlighted code on the server.
            Fumadocs 的 `Pre` 只补充以下布局类，但自身是客户端组件；
            使用等价原生元素可让高亮代码保留在服务端。 */}
        <pre className="min-w-full w-max *:flex *:flex-col">{codeChildren}</pre>
      </div>
    </figure>
  );
}

function getFallbackTitle(children: ReactNode) {
  const firstLine = getTextContent(children).split(/\r?\n/)[0] ?? '';

  return getFilePathFromCodeTitleLine(firstLine);
}

function getTextContent(node: ReactNode): string {
  if (typeof node === 'string' || typeof node === 'number') return String(node);
  if (Array.isArray(node)) return node.map(getTextContent).join('');
  if (isValidElement<{ children?: ReactNode }>(node)) return getTextContent(node.props.children);

  return '';
}

function stripFallbackTitleLine(children: ReactNode) {
  const state = { stripped: false };

  return stripFirstCodeLine(children, state);
}

function stripFirstCodeLine(node: ReactNode, state: { stripped: boolean }): ReactNode {
  if (state.stripped || node == null || typeof node === 'boolean') return node;
  if (Array.isArray(node)) return node.map((child) => stripFirstCodeLine(child, state));
  if (!isValidElement<{ children?: ReactNode }>(node)) return node;

  const element = node as ReactElement<{ children?: ReactNode }>;
  const nextChildren =
    element.type === 'code'
      ? stripFirstLineChildren(element.props.children, state)
      : stripFirstCodeLine(element.props.children, state);

  if (nextChildren === element.props.children) return node;

  return cloneElement(element, undefined, nextChildren);
}

function stripFirstLineChildren(children: ReactNode, state: { stripped: boolean }) {
  const nextChildren: ReactNode[] = [];
  let consumedFirstLine = false;
  let shouldDropLeadingBreak = false;

  state.stripped = true;

  for (const child of Children.toArray(children)) {
    if (!consumedFirstLine) {
      consumedFirstLine = true;

      if (typeof child === 'string') {
        const remainingText = child.replace(/^[^\r\n]*(?:\r?\n)?/, '');
        if (remainingText.length > 0) nextChildren.push(remainingText);
      } else {
        shouldDropLeadingBreak = true;
      }

      continue;
    }

    if (shouldDropLeadingBreak && typeof child === 'string') {
      const remainingText = child.replace(/^\r?\n/, '');
      shouldDropLeadingBreak = false;
      if (remainingText.length > 0) nextChildren.push(remainingText);
      continue;
    }

    shouldDropLeadingBreak = false;
    nextChildren.push(child);
  }

  return nextChildren;
}
