/**
 * Custom code block that always renders a top header bar with:
 * - Language icon (from Shiki transformerIcon)
 * - File path (only when set via remark-code-title)
 * - Copy button
 *
 * 自定义代码块，始终渲染顶部横条，包含：
 * - 编程语言图标（由 Shiki transformerIcon 设置）
 * - 文件路径（仅当通过 remark-code-title 设置时显示）
 * - 复制按钮
 */

'use client';

import { Pre } from 'fumadocs-ui/components/codeblock';
import { useTranslations } from 'fumadocs-ui/contexts/i18n';
import { useCopyButton } from 'fumadocs-ui/utils/use-copy-button';
import { Check, Clipboard } from 'lucide-react';
import { type ComponentProps, type ReactNode, useRef } from 'react';
import { getLanguageDisplayName } from '@/lib/language-mapping';

interface CodeBlockPreProps extends ComponentProps<'pre'> {
  title?: string;
  icon?: ReactNode | string;
  lang?: string;
}

export function CustomCodeBlock(props: CodeBlockPreProps) {
  const { children, title, icon, lang, className, ...rest } = props;
  const areaRef = useRef<HTMLDivElement>(null);
  const hasTitle = typeof title === 'string' && title.length > 0;
  const language = typeof lang === 'string' ? getLanguageDisplayName(lang) : null;

  // Glass code block wrapper keeps page ambient colors visible without changing Shiki markup.
  // 代码块玻璃外壳在不改变 Shiki 结构的前提下，让页面环境色保持可见。
  return (
    <figure
      dir="ltr"
      tabIndex={-1}
      className={`my-4 glass-codeblock rounded-xl shiki relative not-prose overflow-hidden text-sm ${className || ''}`}
      {...rest}
    >
      <div className="flex text-fd-muted-foreground items-center gap-2 h-9.5 border-b px-4">
        {typeof icon === 'string' ? (
          // biome-ignore lint/security/noDangerouslySetInnerHtml: icon HTML is generated by fumadocs Shiki transformer
          <div className="[&_svg]:size-3.5" dangerouslySetInnerHTML={{ __html: icon }} />
        ) : icon ? (
          <div className="[&_svg]:size-3.5">{icon}</div>
        ) : null}
        {hasTitle ? (
          <figcaption className="flex-1 truncate">{title}</figcaption>
        ) : language ? (
          <span className="flex-1 text-xs font-medium">{language}</span>
        ) : (
          <span className="flex-1" />
        )}
        <CopyButton containerRef={areaRef} />
      </div>
      {/* biome-ignore lint/a11y/useSemanticElements: region role matches fumadocs CodeBlock */}
      <div
        ref={areaRef}
        role="region"
        // biome-ignore lint/a11y/noNoninteractiveTabindex: matches fumadocs CodeBlock behavior
        tabIndex={0}
        className="text-[0.8125rem] py-3.5 overflow-auto max-h-[600px] fd-scroll-container focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-fd-ring"
        style={{
          counterSet: (rest as Record<string, unknown>)['data-line-numbers']
            ? `line ${Number((rest as Record<string, unknown>)['data-line-numbers-start'] ?? 1) - 1}`
            : undefined,
        }}
      >
        <Pre>{children}</Pre>
      </div>
    </figure>
  );
}

function CopyButton({ containerRef }: { containerRef: React.RefObject<HTMLDivElement | null> }) {
  const t = useTranslations();
  const [checked, onClick] = useCopyButton(() => {
    const pre = containerRef.current?.getElementsByTagName('pre').item(0);
    if (!pre) return;
    const clone = pre.cloneNode(true) as HTMLElement;
    clone.querySelectorAll('.nd-copy-ignore').forEach((node) => {
      node.replaceWith('\n');
    });
    navigator.clipboard.writeText(clone.textContent ?? '');
  });

  return (
    <button
      type="button"
      data-checked={checked || undefined}
      className="inline-flex items-center justify-center rounded-md p-1 text-fd-muted-foreground hover:text-fd-accent-foreground hover:bg-fd-accent data-checked:text-green-600 data-checked:bg-green-500/10 dark:data-checked:text-green-400 dark:data-checked:bg-green-500/15 transition-all duration-200 cursor-pointer active:scale-95"
      aria-label={checked ? t.codeBlockCopied : t.codeBlockCopy}
      onClick={onClick}
    >
      {checked ? (
        <Check className="size-3.5 animate-in zoom-in-50 duration-200" />
      ) : (
        <Clipboard className="size-3.5" />
      )}
    </button>
  );
}
