// Mermaid diagram renderer with zoom / pan / reset / maximize controls.
// Initializes mermaid on mount and re-renders whenever the chart source or
// theme changes. Falls back to raw text on error.
// Mermaid 图表渲染器（带缩放 / 拖动 / 重置 / 视口内放大控制）。挂载时
// 初始化 mermaid，当图表源码或主题变化时重新渲染。出错时回退为原始文本。

'use client';

import { useI18n } from 'fumadocs-ui/contexts/i18n';
import { Maximize, Minimize, RotateCcw, ZoomIn, ZoomOut } from 'lucide-react';
import { useTheme } from 'next-themes';
import { type CSSProperties, useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { getPageDictionary } from '@/dictionaries';
import { useFitCanvasScale } from '@/lib/hooks/use-fit-canvas-scale';
import { useMermaidMaximize } from '@/lib/hooks/use-mermaid-maximize';
import { useMermaidRender } from '@/lib/hooks/use-mermaid-render';
import { useSvgViewBoxExpander } from '@/lib/hooks/use-svg-viewbox-expander';
import { useZoomAndPan } from '@/lib/hooks/use-zoom-and-pan';
import { resolveLocale } from '@/lib/i18n';

export function Mermaid({ chart }: { chart: string }) {
  const wrapperRef = useRef<HTMLDivElement>(null);
  const inPageWrapperRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLDivElement>(null);
  const [mounted, setMounted] = useState(false);

  const { resolvedTheme } = useTheme();
  const { locale } = useI18n();
  // Locale from fumadocs i18n context is a string; resolve to a valid Locale
  // and pull labels from the shared dictionary (single source of truth).
  // fumadocs i18n 上下文返回的 locale 为字符串，统一解析为合法 Locale
  // 后从共享字典（唯一来源）取工具栏文案。
  const labels = getPageDictionary(resolveLocale(locale));

  useEffect(() => {
    setMounted(true);
  }, []);

  const svgContent = useMermaidRender(chart, resolvedTheme === 'dark' ? 'dark' : 'default');
  const {
    scale,
    setScale,
    pan,
    isDragging,
    zoomIn,
    zoomOut,
    resetZoom,
    handlePointerDown,
    handlePointerMove,
    endDrag,
    canZoomOut,
    canZoomIn,
    canReset,
  } = useZoomAndPan();
  const { svgNatural } = useSvgViewBoxExpander(svgContent, inPageWrapperRef, wrapperRef);
  const { isMaximized, toggleMaximize } = useMermaidMaximize(scale, setScale, svgNatural);
  useFitCanvasScale(svgNatural, canvasRef, isMaximized);

  // CSS custom properties drive the zoom target's *layout* size and the
  // pan transform. `--svg-w` / `--svg-h` MUST be unit-bearing `<length>`s.
  // CSS 变量驱动 zoom 目标的*布局*尺寸与平移。`--svg-w` / `--svg-h` 必须是带单位的 `<length>`。
  const zoomStyle = {
    '--svg-w': `${svgNatural.width}px`,
    '--svg-h': `${svgNatural.height}px`,
    '--mermaid-scale': scale,
    '--mermaid-pan-x': `${pan.x}px`,
    '--mermaid-pan-y': `${pan.y}px`,
  } as CSSProperties;

  const canvasAndToolbar = (
    <>
      <div
        ref={canvasRef}
        className="mermaid-canvas"
        data-dragging={isDragging || undefined}
        onPointerDown={handlePointerDown}
        onPointerMove={handlePointerMove}
        onPointerUp={endDrag}
        onPointerCancel={endDrag}
      >
        <div className="mermaid-zoom-target" style={zoomStyle}>
          {svgContent ? (
            <div
              className="mermaid-svg-host"
              // biome-ignore lint/security/noDangerouslySetInnerHtml: SVG markup is generated by mermaid from the page's own chart source, not untrusted input.
              dangerouslySetInnerHTML={{ __html: svgContent }}
            />
          ) : (
            <pre className="mermaid-fallback">{chart}</pre>
          )}
        </div>
      </div>

      <div role="toolbar" aria-label={labels.mermaidToolbar} className="mermaid-toolbar glass-chip">
        <button
          type="button"
          onClick={zoomOut}
          disabled={!canZoomOut}
          aria-label={labels.mermaidZoomOut}
          className="mermaid-toolbar__btn"
        >
          <ZoomOut className="size-4" />
        </button>
        <span aria-live="polite" className="mermaid-toolbar__scale tabular-nums">
          {Math.round(scale * 100)}%
        </span>
        <button
          type="button"
          onClick={zoomIn}
          disabled={!canZoomIn}
          aria-label={labels.mermaidZoomIn}
          className="mermaid-toolbar__btn"
        >
          <ZoomIn className="size-4" />
        </button>
        <span aria-hidden="true" className="mermaid-toolbar__divider" />
        <button
          type="button"
          onClick={resetZoom}
          disabled={!canReset}
          aria-label={labels.mermaidReset}
          className="mermaid-toolbar__btn"
        >
          <RotateCcw className="size-4" />
        </button>
        <button
          type="button"
          onClick={toggleMaximize}
          aria-label={isMaximized ? labels.mermaidRestore : labels.mermaidMaximize}
          className="mermaid-toolbar__btn"
        >
          {isMaximized ? <Minimize className="size-4" /> : <Maximize className="size-4" />}
        </button>
      </div>
    </>
  );

  const inPageWrapper = (
    <div
      ref={inPageWrapperRef}
      className="mermaid-wrapper not-prose group/mermaid my-4"
      data-page-renderer
      data-hidden={isMaximized || undefined}
      aria-hidden={isMaximized || undefined}
    >
      {canvasAndToolbar}
    </div>
  );

  const maximizedWrapper = (
    <div ref={wrapperRef} className="mermaid-wrapper not-prose group/mermaid my-4" data-maximized>
      {canvasAndToolbar}
    </div>
  );

  const maximizedBackdrop = <div className="mermaid-maximized-backdrop" aria-hidden="true" />;

  if (mounted && isMaximized && typeof document !== 'undefined') {
    return (
      <>
        {inPageWrapper}
        {createPortal(maximizedBackdrop, document.body)}
        {createPortal(maximizedWrapper, document.body)}
      </>
    );
  }
  return inPageWrapper;
}
